title: Presentations
email: brandon.amos.cs@gmail.com
description: My presentations
author: Brandon Amos

twitter_username: brandondamos
github_username:  bamos

domain: bamos.github.io
url: https://bamos.github.io
baseurl: /presentations

markdown: kramdown
theme: minima
plugins: []
safe: false

future: true

collections:
  presentations:
    output: true
    permalink: /:path:output_ext

defaults:
  - scope:
      path: ""
      type: presentations
    values:
      layout: post
